english = [
    "choose",
    "favor",
    "darkness",
    "killing",
    "leave",
    "try",
    "drive out",
    "well",
    "sit",
    "call",
    "class",
    "flight",
    "consider",
    "color",
    "flower",
    "word",
    "at some time",
    "friendship",
    "produce",
    "often",
    "beget",
    "therefore",
    "because of",
    "star",
    "raise up",
    "son",
    "golden",
    "by",
    "admit",
    "mountain",
    "choose",
    "citizen",
    "come to",
    "flee",
    "people",
    "beget",
    "speech",
    "building",
    "faithful",
    "determine",
    "thousand",
    "get ready",
    "not know",
    "from all sides",
    "moreover",
    "gift",
    "around",
    "seek",
    "praise",
    "since",
    "look back",
    "set forth",
    "demand",
    "commit a wrong",
    "deny",
    "fortress",
    "too much",
    "one’s own",
    "guilt",
    "shore",
    "teach",
    "sad",
    "lead forth",
    "or else",
    "swift",
    "arrive",
    "lie open",
    "ancient",
    "ugly",
    "honor",
    "fit",
    "deceive",
    "work",
    "only",
    "destroy",
    "foreign",
    "mind",
    "be a slave",
    "without",
    "write",
    "today",
    "behold!",
    "complain of",
    "origin",
    "present",
    "it is pleasing",
    "while",
    "fight",
    "raise up",
    "so great",
    "unpleasant",
    "sing",
    "care",
    "think",
    "scarcely",
    "abundance",
    "to hope",
    "master",
    "produce",
    "power",
    "judge",
    "remain",
    "commander",
    "return",
    "huge",
    "danger",
    "indeed",
    "after",
    "soft",
    "assemble",
    "farthest",
    "go to",
    "farthest",
    "poet",
    "however",
    "middle",
    "kill",
    "until",
    "once",
    "for this reason",
    "pleasure",
    "long for",
    "show",
    "be present",
    "side",
    "excel",
    "take position",
    "penalty",
    "citadel",
    "true",
    "look",
    "against",
    "ground",
    "continue",
    "fill in",
    "province",
    "turn back",
    "gather",
    "hold",
    "right",
    "publish",
    "influence",
    "iron",
    "go",
    "of what kind?",
    "torch",
    "send away",
    "cattle",
    "easy",
    "the common people",
    "be born",
    "flee",
    "whether",
    "learn",
    "enough",
    "join",
    "undertake",
    "pure",
    "say",
    "year",
    "for",
    "wife",
    "star",
    "exile",
    "naked",
    "even as",
    "line of march",
    "understand",
    "one each",
    "again",
    "train",
    "three",
    "tribune",
    "soon",
    "be empty",
    "hold up",
    "finally",
    "slow",
    "crime",
    "necessity",
    "ox",
    "agreement",
    "prayers",
    "divine",
    "end",
    "stream",
    "breath",
    "bring about",
    "so great",
    "hesitate",
    "deceptive",
    "rumor",
    "to fear",
    "join",
    "put",
    "head",
    "spouse",
    "bond",
    "sad",
    "praetor",
    "furnish",
    "change",
    "well-known",
    "send forth",
    "judge",
    "begin",
    "interrogate",
    "weight",
    "be eager",
    "encircle",
    "formerly",
    "sound",
    "song",
    "who? what? which?",
    "use",
    "load",
    "certainly",
    "send away",
    "command",
    "not yet",
    "weep",
    "think",
    "wisdom",
    "edge",
    "citizenship",
    "doubtful",
    "safe",
    "wave",
    "originator",
    "right",
    "in vain",
    "ear",
    "point out",
    "booty",
    "take back",
    "take away",
    "close",
    "light",
    "grove",
    "ten",
    "divine will",
    "it is proper",
    "labor",
    "know",
    "collect",
    "go forth",
    "winter",
    "unfriendly",
    "delight",
    "skill",
    "sister",
    "join",
    "light",
    "such",
    "before",
    "and so",
    "equal",
    "powerful",
    "sense of shame",
    "furnish",
    "ashes",
    "river",
    "establish",
    "new",
    "be accustomed",
    "thus",
    "within",
    "sick",
    "it is right",
    "send",
    "eye",
    "break",
    "far",
    "worth",
    "tear",
    "earth",
    "disturb",
    "go back",
    "to that place",
    "appear",
    "too little",
    "kill",
    "to fear",
    "defend",
    "be away",
    "verdict",
    "fight",
    "give to",
    "sure",
    "learn",
    "back",
    "number",
    "place of burial",
    "guest",
    "enter",
    "give to",
    "tender",
    "always",
    "shape",
    "flow",
    "sun",
    "weep",
    "weep",
    "right",
    "rule",
    "forehead",
    "whoever",
    "stone",
    "period of time",
    "price",
    "learn",
    "deed",
    "lie",
    "hair",
    "at once",
    "custom",
    "slow",
    "fall upon",
    "guide",
    "begin",
    "only",
    "attack",
    "just as",
    "fire",
    "short",
    "judgment",
    "level surface",
    "at that place",
    "fatherland",
    "broad",
    "passion",
    "fall",
    "touch",
    "be a slave",
    "right",
    "wind",
    "sharp",
    "friendly",
    "excessively",
    "go astray",
    "footstep",
    "distinguished",
    "a living being",
    "toil",
    "business",
    "from where",
    "woman",
    "entire",
    "go",
    "run to meet",
    "commit a wrong",
    "next",
    "household master",
    "lucky",
    "fate",
    "witness",
    "force",
    "be eager",
    "wise",
    "complete",
    "truly",
    "whatever",
    "neighboring",
    "put in",
    "aspect",
    "night",
    "send forth",
    "able",
    "report",
    "badly",
    "banquet",
    "think",
    "near",
    "eagerness",
    "soldier",
    "avoid",
    "long for",
    "bank of a river",
    "as if",
    "distinguished",
    "conqueror",
    "pain",
    "friendly",
    "take up",
    "move",
    "yoke",
    "help",
    "pour out",
    "voice",
    "sweet",
    "service",
    "be silent",
    "come to",
    "account",
    "not",
    "how great?",
    "straight",
    "spare",
    "letter",
    "nourish",
    "seat",
    "solemn promise",
    "flame",
    "altar",
    "free from care",
    "foreigner",
    "nourish",
    "likewise",
    "personal",
    "give to",
    "strike",
    "terrify",
    "ask",
    "try",
    "world",
    "copper",
    "certainly",
    "by chance",
    "sky",
    "divide",
    "sign",
    "go astray",
    "bad",
    "sea",
    "conversation",
    "course",
    "prepare",
    "scatter",
    "any",
    "few",
    "service",
    "let go",
    "save",
    "yield",
    "sure",
    "receive",
    "overbearing",
    "space",
    "equally",
    "earlier",
    "rage",
    "suddenly",
    "seize",
    "launch",
    "tongue",
    "pick out",
    "consul",
    "hard",
    "hatred",
    "walls",
    "valor",
    "empty",
    "air",
    "before",
    "money",
    "those above",
    "wrath",
    "blood",
    "be strong",
    "bounty",
    "other of two",
    "battle",
    "live",
    "empty",
    "compel",
    "demand",
    "riches",
    "messenger",
    "obey",
    "when?",
    "climb up",
    "army",
    "watch",
    "(adv",
    "forbid",
    "hasten",
    "sword",
    "pour",
    "build",
    "take away",
    "beautiful",
    "stretch",
    "bring upon",
    "from there",
    "common",
    "damage",
    "daughter",
    "pray",
    "white",
    "town",
    "worthy",
    "divine",
    "it is right",
    "youth",
    "perhaps",
    "envy",
    "training",
    "think",
    "climb down",
    "overcome",
    "above",
    "holy",
    "formerly",
    "to hope",
    "besides",
    "carry away",
    "help",
    "horse",
    "put forth",
    "girl",
    "up to",
    "because",
    "demand",
    "book",
    "be born",
    "fresh",
    "doubtful",
    "present with a gift",
    "dare",
    "like",
    "step in",
    "shade",
    "back",
    "be of use",
    "bring back",
    "go back",
    "long",
    "allow",
    "contain",
    "help",
    "vine",
    "water",
    "flaw",
    "lead to",
    "sharp",
    "stand",
    "urge",
    "take up",
    "hear",
    "hold",
    "foot",
    "speak",
    "pure",
    "clear",
    "for which reason",
    "material",
    "gold",
    "divide",
    "therefore",
    "wandering",
    "middle",
    "rich",
    "frequent",
    "how much?",
    "necessary",
    "deed",
    "hunger",
    "carry",
    "to fear",
    "holy",
    "free from care",
    "complain of",
]